### ISSUE TITLE
CDN with gh-pages

### ISSUE THREAD

**Issue by deamme** [imthenachoman/nAnimation#1]
Could be cool with a cdn made in gh-pages like I did with my library. http://deamme.github.io/StyleJS/style.js. This make it easy to test a library in e.g www.jsfiddle.net

**Comment by imthenachoman** [comment]
How did you create this? I can create the gh-page but not sure how to add files that can be linked to.

**Comment by imthenachoman** [comment]
How is this? http://imthenachoman.github.io/nAnimation

**Comment by deamme** [comment]
Wow, I was only asking for cdn. What a nice page you got there. Very nice :D! You can close this!

**Comment by imthenachoman** [comment]
Thanks! Luckily GitHub offers a wizard to create pages using the existing README.md so it was really easy.
